# Build Depdendancies
FROM node:20-alpine AS production

# Create directory and install Turbo & TypeScript
WORKDIR /app
RUN npm install -g turbo@2.1.3

# Install dependancies
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy monorepo in and prune dependencies
COPY . .
RUN turbo prune --scope=@flash-cards-system/client --docker

# RUN yarn install --dev
RUN cd client && yarn add typescript --dev
RUN cd client && yarn add vite --dev

# Compile production build
RUN yarn client:build

# Expose port
EXPOSE 4173

# Start server
CMD ["yarn", "client:preview"]