version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      target: production
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
      PORT: 80
      DATABASE_URL: "file:./dev.db"
      JWT_SECRET: "9jzInZSfM3UbtdL1J1cbm20dy6VqvrfLtzQHFZxv"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      target: production
    ports:
      - "81:80"
    environment:
      NODE_ENV: production
    depends_on:
      - server
