# --- Build Stage ---
FROM node:18-alpine AS builder

# Create directory
WORKDIR /monorepo

# Copy in package;json and yarn.lock
COPY package.json yarn.lock ./

# Copy in monorepo code
COPY . .

# Install dependencies for the server & database workspace only
RUN cd server && yarn install --frozen-lockfile
RUN cd database && yarn install --frozen-lockfile

# Carry out build tasks
RUN cd server && yarn run build
RUN cd database && yarn run database:migrate

# --- Production Stage ---
FROM node:18-alpine AS production

# Create directory
WORKDIR /server

# Copy built files, package.json, and yarn.lock from builder
COPY --from=builder /monorepo/server/dist /server/dist/
COPY --from=builder /monorepo/server/package.json /monorepo/yarn.lock /server/

# Install only production dependencies
RUN yarn install --production --frozen-lockfile
RUN yarn add @prisma/client

# Copy prisma client and database
COPY --from=builder /monorepo/node_modules/.prisma /server/node_modules/.prisma
COPY --from=builder /monorepo/database/prisma/dev.db /server/prisma/dev.db

# Expose port
EXPOSE 80

# Start server
CMD ["node", "dist/Server.js"]



# # Create production image
# FROM node:20-alpine AS production

# # Create directory and install Turbo
# WORKDIR /app

# # Install dependancies
# COPY package.json yarn.lock ./
# RUN yarn install --frozen-lockfile
# RUN yarn global add turbo

# # Copy monorepo in and prune dependencies
# COPY . .
# RUN turbo prune --scope=@flash-cards-system/server --docker

# # Instal required build dependencies
# RUN cd server && yarn add typescript tsx prisma @prisma/client -D

# # Compile production build
# RUN yarn server:build

# # Run database migration and seeder
# RUN yarn db:migrate

# # Expose port
# EXPOSE 80

# # Start server
# CMD ["yarn", "server:start"]