# --- Build Stage ---
FROM node:20-alpine AS builder

# Create directory
WORKDIR /monorepo

# Copy in package;json and yarn.lock
COPY package.json yarn.lock ./

# Copy in monorepo code
COPY . .

# Install dependencies for the client workspace only
RUN cd client && yarn install --frozen-lockfile

# Carry out build task
RUN cd client && yarn run build

# --- Production Stage ---
FROM nginx:alpine AS production

# Copy built files
COPY --from=builder /monorepo/client/dist /usr/share/nginx/html

# Expose port
EXPOSE 80



# # Build Depdendancies
# FROM node:20-alpine AS production

# # Create directory
# WORKDIR /app

# # Install dependancies
# COPY package.json yarn.lock ./
# RUN yarn install --frozen-lockfile
# RUN yarn global add turbo

# # Copy monorepo in and prune dependencies
# COPY . .
# RUN turbo prune --scope=@flash-cards-system/client --docker

# # Install build dependencies
# RUN cd client && yarn add typescript vite -D

# # Compile production build
# RUN yarn client:build

# # Expose port
# EXPOSE 81

# # Start server
# CMD ["yarn", "client:preview"]